name: jobjet
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.0-262.2.beta <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  mockito: ^5.4.2
  sizer: ^2.0.15
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  flutter_svg: ^2.0.4
  formz: ^0.6.0
  heroicons: ^0.9.0
  cloud_firestore: ^4.8.4
  url_launcher: ^6.1.14

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/images/
  fonts:
    - family: ResistSansText
      fonts:
        - asset: assets/fonts/ResistSansText-Medium.ttf
