import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkznDMkmCy_sFwRgWEp4YjwyZO8Fvq6ck',
    appId: '1:116293257588:web:194aeaa4d4edbb976fc421',
    messagingSenderId: '116293257588',
    projectId: 'jobjet-54fa5',
    authDomain: 'jobjet-54fa5.firebaseapp.com',
    storageBucket: 'jobjet-54fa5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqS0BsxusI-Aq_qcsScoUAgs8gEnM_-YU',
    appId: '1:116293257588:android:f8ccce53d6aace6f6fc421',
    messagingSenderId: '116293257588',
    projectId: 'jobjet-54fa5',
    storageBucket: 'jobjet-54fa5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-gS_g7Sa78A2XJ07pW4qXOuJAxaohcO0',
    appId: '1:116293257588:ios:311f44cbb2b829ad6fc421',
    messagingSenderId: '116293257588',
    projectId: 'jobjet-54fa5',
    storageBucket: 'jobjet-54fa5.appspot.com',
    iosClientId:
        '116293257588-kpqoua2im2vq03ugc5omtm0njmqqlv38.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobjet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-gS_g7Sa78A2XJ07pW4qXOuJAxaohcO0',
    appId: '1:116293257588:ios:1996ebd89c5eae106fc421',
    messagingSenderId: '116293257588',
    projectId: 'jobjet-54fa5',
    storageBucket: 'jobjet-54fa5.appspot.com',
    iosClientId:
        '116293257588-kokmsgh3g2dkgm7p72q93e9c0s6hvvsn.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobjet.RunnerTests',
  );
}
